server:
  port: 8765
spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/spring-boot
  #配置redis
    redis:
      database: 0
      host: 192.168.31.71
      port: 6379
      timeout: 0
      password: password
      pool:
        #最大连接数
        max-active: 8 
        #阻塞时间
        max-wait: -1 
        #最大空闲
        max-idle: 8 
        #最小空闲
        min-idle: 0 
#配置日志
logging:
  config: classpath:logback-close.xml #如果使用该配置 所有日志将写入redis 
 # path: /com/yangyiwei
  #level:
  #  com.chat.springboot: debug
