#eureka:
  #client:
   # serviceUrl:
    #  defaultZone: http://localhost:8761/eureka/
spring:
  #配置阿里巴巴连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-boot?characterEncoding=utf8
    username: yangyiwei
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
 
  #配置热部署工具   
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: templates/**
  
